// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmt29RkDZkG95c3y4fJ4r8IQBe0cuNWPc',
    appId: '1:532834862834:web:be9a41b6f3dd7b3412326b',
    messagingSenderId: '532834862834',
    projectId: 'lien-fd159',
    authDomain: 'lien-fd159.firebaseapp.com',
    storageBucket: 'lien-fd159.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdqE_8T_K90TKrrGAd0gSTkDyZyqCLxO0',
    appId: '1:532834862834:android:98f390f01046ad8212326b',
    messagingSenderId: '532834862834',
    projectId: 'lien-fd159',
    storageBucket: 'lien-fd159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRQE7mGrkP0MQkSD5VK-mQAGmjVTKbV0',
    appId: '1:532834862834:ios:922245509702484112326b',
    messagingSenderId: '532834862834',
    projectId: 'lien-fd159',
    storageBucket: 'lien-fd159.firebasestorage.app',
    iosBundleId: 'com.example.kotodamaRadar1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnRQE7mGrkP0MQkSD5VK-mQAGmjVTKbV0',
    appId: '1:532834862834:ios:65458a3d9b05ab9d12326b',
    messagingSenderId: '532834862834',
    projectId: 'lien-fd159',
    storageBucket: 'lien-fd159.firebasestorage.app',
    iosBundleId: 'com.example.kotodamaRadar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmt29RkDZkG95c3y4fJ4r8IQBe0cuNWPc',
    appId: '1:532834862834:web:3decea44387c24ee12326b',
    messagingSenderId: '532834862834',
    projectId: 'lien-fd159',
    authDomain: 'lien-fd159.firebaseapp.com',
    storageBucket: 'lien-fd159.firebasestorage.app',
  );

}